"""Add details, price, authenticity_verified to bags

Revision ID: 19637acabf9d
Revises: db3aaab9c110
Create Date: 2025-07-02 14:04:20.967753

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = '19637acabf9d'
down_revision = 'db3aaab9c110'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bag', sa.Column('details', sqlmodel.sql.sqltypes.AutoString(length=1000), nullable=True))
    op.add_column('bag', sa.Column('price', sa.Float(), nullable=True))
    op.add_column('bag', sa.Column('authenticity_verified', sa.Boolean(), nullable=False, server_default='0'))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('bag', 'authenticity_verified')
    op.drop_column('bag', 'price')
    op.drop_column('bag', 'details')
    # ### end Alembic commands ### 